---
- name: REST API Put Config
  hosts: r3
  gather_facts: false
  tasks:
    - name: User input
      ansible.builtin.pause:
        prompt: Enter Hostname
      register: hostname_input
    
    - name: Setfact for hostname
      ansible.builtin.set_fact:
        hostname_str: "{{ hostname_input.user_input }}"

    - name: Put Config
      ansible.builtin.uri:
        url: https://{{ ansible_host }}/restconf/data/Cisco-IOS-XE-native:native/hostname
        method: PUT
        body: "{{ lookup('template', 'templates/hostname.j2')}}"
        body_format: json
        headers:
          Accept: application/yang-data+json
          Authorization: "Basic YWRtaW46YWRtaW4="
          Content-Type: application/yang-data+json
        validate_certs: false
        status_code: 204
      register: device_conf

    - name: Print data
      ansible.builtin.debug:
        msg: 
          - "{{ device_conf }}"