---
- name: REST API Delete Config
  hosts: r3
  gather_facts: false
  tasks:
    - name: Delete Config
      ansible.builtin.uri:
        url: https://{{ ansible_host }}/restconf/data/Cisco-IOS-XE-native:native/interface/Loopback=1004
        method: DELETE
        headers:
          Accept: application/yang-data+json
          Authorization: "Basic YWRtaW46YWRtaW4="
        validate_certs: false
        status_code: 204,201
      register: device_conf

    - name: Print data
      ansible.builtin.debug:
        msg: 
          - "{{ device_conf }}"