---
- name: Configure intf name
  hosts: r1
  gather_facts: false
  tasks:
    - name: Configure intf
      cisco.ios.ios_config:
        src: templates/intf_conf.j2
      with_items: "{{ interface_list }}"
      register: intf_config
    
    - name: Print Command Output
      ansible.builtin.debug:
        msg: "{{ intf_config }}"