---
- name: Configure intf name
  hosts: r1
  gather_facts: false
  tasks:
    - name: Configure intf
      cisco.ios.ios_config:
        lines:
          - description Gi3_description
          - ip address 100.3.3.3 255.255.255.0
        parents: interface GigabitEthernet0/3
        save_when: changed
      register: intf_config

    - name: Print Command Output
      ansible.builtin.debug:
        msg: "{{ intf_config }}"