- name: Handlers demo
  hosts: r2
  gather_facts: false
  tasks:
########  handlers ##########################
    - name: L3 Config
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
            ipv4:
              - address: 10.10.10.2/28
        state: merged
      register: l3_config_output
      notify:
        - Print Command

    - name: Print Output
      ansible.builtin.debug:
        msg: "{{ l3_config_output }}"

  handlers:
    - name: Print Command
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: '/home/dev/ansible_masterclass/18_handlers,block,assert/backup'
        save_when: always
      listen: ip change post action

    - name: Print Command
      ansible.builtin.debug:
        msg: "{{ l3_config_output.commands }}"
      listen: ip change post action

