- name: hostname rm demo
  hosts: gns_r1
  gather_facts: false
  tasks: 
# ######### merged ##########################
    - name: Configure Hostname
      cisco.ios.ios_hostname:
        config:
          hostname: Router1
        state: replaced
      register: host_conf
    
    - name: Print command output
      ansible.builtin.debug:
        msg: "{{ host_conf }}"

# ######### gathered ##########################
    - name: Gathered demo
      cisco.ios.ios_hostname:
        state: gathered
      register: host_conf
    
    - name: Print gathered output
      ansible.builtin.debug:
        msg: "{{ host_conf }}"

######### Rendered ##########################
    - name: rendered demo
      cisco.ios.ios_hostname:
        config:
          hostname: Router1
        state: rendered
      register: host_conf
    
    - name: Print rendered output
      ansible.builtin.debug:
        msg: "{{ host_conf }}"        

############ Backup the config ###########
    - name: backup config
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: r1.cfg

######### Parsed ##########################
    - name: parsed demo
      cisco.ios.ios_hostname:
        running_config: "{{ lookup('file', 'backup/r1.cfg') }}"
        state: parsed
      register: host_conf
    
    - name: Print parsed output
      ansible.builtin.debug:
        msg: "{{ host_conf }}"       

######### deleted ##########################
    - name: deleted demo
      cisco.ios.ios_hostname:
        state: deleted
      register: host_conf
    
    - name: Print deleted output
      ansible.builtin.debug:
        msg: "{{ host_conf }}"          