---
- name: Strategies demo
  hosts: all
  gather_facts: false
  strategy: linear
  serial:
    - 20%
    - 30%
    - 20%
  tasks:
    - name: Add delay
      wait_for:
        timeout: "{{ add_delay }}"

    - name: Print hostname
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"