---
- name: Block rescue Demo
  hosts: routers
  gather_facts: false
  tasks:
  - name: Use the blocks API
    community.general.slack:
      token: T06E969G4AH/B0700C2V9F0/pCFRkTCJoscGpEUPEkuqJdOz
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: |-
              *System load*
              Display my system load on host A and B
        - type: context
          elements:
          - type: mrkdwn
            text: |-
              *System A*
              load average: 0,74, 0,66, 0,63
          - type: mrkdwn
            text: |-
              *System B*
              load average: 5,16, 4,64, 2,43
  #   - name: Block for vIOS Devices
  #     block:
  #       - name: L3 Config
  #         cisco.ios.ios_l3_interfaces:
  #           config:
  #             - name: GigabitEthernet0/1
  #               ipv4:
  #                 - address: "{{ sample_ip }}"
  #         register: intf_config
  #         notify: ip change post action

  #     rescue:
  #       - name: Print fail message
  #         ansible.builtin.debug:
  #           msg: 
  #             - "Task has failed"
  #             - "{{ intf_config }}"
          
  #     always:
  #       - name: Print conf output always
  #         ansible.builtin.debug:
  #           msg:
  #             - "{{ intf_config }}"


  # handlers:
  #   - name: Save Config
  #     cisco.ios.ios_config:
  #       backup: true
  #       backup_options:
  #         dir_path: '/home/dev/ansible_masterclass/18_handlers,block,assert/backup'
  #       save_when: always
  #     listen: ip change post action

  #   - name: Print Command
  #     ansible.builtin.debug:
  #       msg: "{{ intf_config.commands }}"
  #     listen: ip change post action